spring:
  profiles:
    active: dev # 指定啟動時載入 application-dev.yaml

  application:
    name: Venue Reservation System # 通用的專案名稱放在這裡

# MyBatis 通用配置也可以放在主檔，除非不同環境有不同的 Mapper 路徑
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: tw.edu.ncu.osa.venue_reservation_service.model.entity
  configuration:
    map-underscore-to-camel-case: true # 自動將 DB 欄位轉為 CamelCase